parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  - group: ${{ parameters.VarGroup }}
  - name: InstrumentPath
    value: c:\survey
  - name: ServerParkName
    value: gusty
  - name: InstrumentName
    value: OPN2101A
  - name: BLAISE_VERSION
    value: Blaise5_8_7_2522

stages:
  - stage: ${{parameters.Environment }}
    displayName: ${{parameters.Environment }} Environment
    jobs:
       - deployment: installBlaise
         displayName: Install Blaise
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self

                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/InstallBlaise.ps1'

                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/CheckBlaiseIsInstalled.ps1'
                    targetType: inline
                    script: write-host $(BlaiseInstalled)
                    
                - script: hello $(BlaiseInstalled)


                