parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  - group: ${{ parameters.VarGroup }}
  - name: InstrumentPath
    value: c:\survey
  - name: ServerParkName
    value: gusty
  - name: InstrumentName
    value: OPN2101A
  - name: BLAISE_VERSION
    value: Blaise5_8_7_2522
  - name: BlaiseInstalled
    value: False

stages:
  - stage: ${{parameters.Environment }}
    displayName: ${{parameters.Environment }} Environment
    jobs:
       - deployment: CheckIfBlaiseIsInstalled
         displayName: Check If Blaise is installed
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self

                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/CheckBlaiseIsInstalled.ps1'
                  name: IsBlaiseInstalled

       - deployment: installBlaise
         displayName: Install Blaise
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         dependsOn: CheckIfBlaiseIsInstalled
         condition: eq(dependencies.CheckIfBlaiseIsInstalled.outputs['IsBlaiseInstalled.BlaiseInstalled'], 'True')
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self
                - task: PowerShell@2
                  inputs:
                    targetType: inline
                    script: Write-Host "Got here"


                