trigger:
- main

stages:
  - stage: Dev
    displayName: Dev Environment
    jobs:
       - deployment: installBlaise
         displayName: Install Blaise
         environment:
          name: Nik
          resourceType: VirtualMachine
          tags: blaise
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self
                    
                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/InstallBlaise.ps1'

                - task: DownloadBuildArtifacts@0
                  inputs:
                    buildType: 'specific'
                    project: 'fbaf94f7-2d40-410a-8a27-de142d8d2313'
                    pipeline: '43'
                    buildVersionToDownload: 'latestFromBranch'
                    branchName: 'refs/heads/master'
                    downloadType: 'single'
                    artifactName: '_AutomatedTests'
                    downloadPath: '$(System.ArtifactsDirectory)'
                
                - task: DownloadSecureFile@1
                  name: gcpkey
                  inputs:
                    secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'
                
                - task: PowerShell@2
                  displayName: Download instrument
                  inputs:
                    targetType: 'inline'
                    script: |
                      Write-Host "Login to GCP"
                         gcloud auth activate-service-account pipeline-bucket-reader@ons-blaise-v2-shared.iam.gserviceaccount.com --key-file=$(gcpkey.secureFilePath)
                         
                         Write-Host "Downloading instrument"
                         gsutil cp gs://ons-blaise-v2-europe-west2-shared-data/OPN2101A.zip c:\survey\OPN2101A.zip

                - task: VisualStudioTestPlatformInstaller@1
                  inputs:
                    packageFeedSelector: 'nugetOrg'
                    versionSelector: 'latestPreRelease'
