trigger:
- pipeline

stages:
  - stage: Dev
    displayName: Dev Environment
    jobs:
       - deployment: installBlaise
         displayName: Install Blaise
         environment: 'Nik1'
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self
                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/hello-world.ps1'
                
                - task: CopyFiles@2
                  inputs:
                    SourceFolder: '$(Agent.BuildDirectory)'
                    Contents: '**'
                    TargetFolder: 'c:\nik'
     