parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  - group: ${{ parameters.VarGroup }}
  - name: InstrumentPath
    value: c:\survey
  - name: ServerParkName
    value: gusty
  - name: InstrumentName
    value: OPN2101A

stages:
  - stage: Dev
    displayName: Dev Environment
    jobs:
       - deployment: installBlaise
         displayName: Install Blaise
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self
                    
                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/hello-world.ps1'
                - powershell: 
                          Write-Host 'Value of GroupName is $(GroupName)'
                          'Value of Second is $(SecondValue)'

       - job: "SmokeTests"
         pool: 
          vmImage: 'windows-latest'
         steps: 
         - task: DownloadSecureFile@1
           displayName: 'Download GCP Key'
           name: gcpkey
           inputs:
              secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'

         - task: DownloadSecureFile@1
           displayName: 'Download secure file'
           name: BlaiseRegistrySettings
           inputs:
              secureFile: blaise.reg

         - powershell: |
            regedit /i /s $(BlaiseRegistrySettings.secureFilePath)	
           displayName: 'Register Blaise License'

         - task: PowerShell@2
           displayName: Download instrument
           inputs:
              targetType: 'inline'
              script: |
                Write-Host "Login to GCP"
                    gcloud auth activate-service-account pipeline-bucket-reader@ons-blaise-v2-shared.iam.gserviceaccount.com --key-file=$(gcpkey.secureFilePath)
                    
                    Write-Host "Downloading instrument"
                    gsutil cp gs://ons-blaise-v2-europe-west2-shared-data/OPN2101A.zip c:\survey\OPN2101A.zip

         - task: VisualStudioTestPlatformInstaller@1
           inputs:
              packageFeedSelector: 'nugetOrg'
              versionSelector: 'latestPreRelease'
              
         - task: DownloadBuildArtifacts@0
           inputs:
              buildType: 'specific'
              project: 'fbaf94f7-2d40-410a-8a27-de142d8d2313'
              pipeline: '43'
              buildVersionToDownload: 'latestFromBranch'
              branchName: 'refs/heads/master'
              downloadType: 'single'
              artifactName: '_AutomatedTests'
              downloadPath: '$(System.ArtifactsDirectory)'

         - task: replacetokens@3
           inputs:
              rootDirectory: '$(System.ArtifactsDirectory)' 
              targetFiles: '**/*Behaviour*.config'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTelemetry: true

         - task: VSTest@2
           displayName: 'Run Blaise Smoke Tests'
           inputs:
             searchFolder: '$(System.ArtifactsDirectory)'
             testAssemblyVer2: |
              **\Blaise.Tests.Behaviour\**\Blaise.Tests.Behaviour.dll
              !**\obj\**
              resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
             runOnlyImpactedTests: false
             uiTests: true
             vsTestVersion: toolsInstaller
             runInParallel: false
             runTestsInIsolation: false
             codeCoverageEnabled: false
             testRunTitle: 'Instrument Test'
           continueOnError: false