trigger:
- pipeline

pool:
  vmImage: 'windows-latest'

stages:
  - stage: Dev
    displayName: Dev Environment
    jobs:
       - deployment: installBlaise
         displayName: Install Blaise
         environment: 'Nik'
         strategy:
          runOnce:
             deploy:
               steps:
                - task: PowerShell@2
                  inputs:
                    filePath: '$(System.DefaultWorkingDirectory)/s/hello-world.ps1'
                
                - task: CopyFiles@2
                  inputs:
                    SourceFolder: '$(System.DefaultWorkingDirectory)'
                    Contents: '**'
                    TargetFolder: 'c:\nik'
     