parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  - group: ${{ parameters.VarGroup }}
  - name: InstrumentPath
    value: c:\survey
  - name: ServerParkName
    value: gusty
  - name: InstrumentName
    value: OPN2101A
  - name: BLAISE_VERSION
    value: Blaise5_8_7_2522


stages:
  - stage: CloudSQLProxy_${{parameters.Environment }}
    displayName: Installation Of Cloud SQL Proxy_${{parameters.Environment }}
    jobs:
       - deployment: CheckIfSQLProxyIsInstalled_Blaise_Gusty_Node
         displayName: Check If SQL proxy is installed
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self

                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/scripts/SqlProxy/CheckCloudSQLProxyIsInstalled.ps1'
                  name: IsSQLProxyInstalled

       - deployment: installSQLProxy_Blaise_Gusty_Node
         displayName: Install SQL proxy
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         dependsOn: CheckIfSQLProxyIsInstalled_Blaise_Gusty_Node
         condition: eq(dependencies.CheckIfSQLProxyIsInstalled_Blaise_Gusty_Node.outputs['Deploy_BLAISE-GUSTY-NODE.IsSQLProxyInstalled.SQLProxyInstalled'], 'False')
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self
              
                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/scripts/SqlProxy/InstallCloudSQLProxy.ps1'
                  name: InstallCloudSQLProxy

       - deployment: CheckIfSQLProxyIsInstalled_RESTAPI
         displayName: Check If SQL proxy is installed
         environment: ${{parameters.Environment }}.RESTAPI
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self

                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/scripts/SqlProxy/CheckCloudSQLProxyIsInstalled.ps1'
                  name: IsSQLProxyInstalled

       - deployment: installSQLProxy_RESTAPI
         displayName: Install SQL proxy
         environment: ${{parameters.Environment }}.RESTAPI
         dependsOn: CheckIfSQLProxyIsInstalled_RESTAPI
         condition: eq(dependencies.CheckIfSQLProxyIsInstalled_RESTAPI.outputs['Deploy_RESTAPI.IsSQLProxyInstalled.SQLProxyInstalled'], 'False')
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self
              
                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/scripts/SqlProxy/InstallCloudSQLProxy.ps1'
                  name: InstallCloudSQLProxy

  - stage: BlaiseInstall_${{parameters.Environment }}
    displayName: ${{parameters.Environment }} Installation Of Blaise
    jobs:
       - deployment: CheckIfBlaiseIsInstalled
         displayName: Check If Blaise is installed
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self

                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/CheckBlaiseIsInstalled.ps1'
                  name: IsBlaiseInstalled

       - deployment: installBlaise
         displayName: Install Blaise
         environment: ${{parameters.Environment }}.BLAISE-GUSTY-NODE
         dependsOn: CheckIfBlaiseIsInstalled
         condition: eq(dependencies.CheckIfBlaiseIsInstalled.outputs['Deploy_BLAISE-GUSTY-NODE.IsBlaiseInstalled.BlaiseInstalled'], 'False')
         strategy:
          runOnce:
             deploy:
               steps:
                - checkout: self

                - task: PowerShell@2
                  inputs:
                    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/InstallBlaise.ps1'

       - job: "SmokeTests"
         dependsOn: installBlaise
         condition: in(dependencies.installBlaise.result, 'Succeeded', 'Skipped')
         variables:
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
          ENV_BLAISE_SERVER_HOST_NAME : $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
         pool: 
          vmImage: 'windows-latest'
         steps: 
         - task: DownloadSecureFile@1
           displayName: 'Download GCP Key'
           name: gcpkey
           inputs:
              secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'

         - task: DownloadSecureFile@1
           displayName: 'Download blaise registry file'
           name: BlaiseRegistrySettings
           inputs:
              secureFile: blaise.reg

         - powershell: |
            regedit /i /s $(BlaiseRegistrySettings.secureFilePath)	
           displayName: 'Register Blaise License'

         - task: PowerShell@2
           displayName: Download test instrument
           inputs:
              targetType: 'inline'
              script: |
                Write-Host "Login to GCP"
                    gcloud auth activate-service-account pipeline-bucket-reader@ons-blaise-v2-shared.iam.gserviceaccount.com --key-file=$(gcpkey.secureFilePath)
                    
                    Write-Host "Downloading instrument"
                    gsutil cp gs://ons-blaise-v2-europe-west2-shared-data/OPN2101A.zip c:\survey\OPN2101A.zip

         - task: VisualStudioTestPlatformInstaller@1
           displayName: Install Visual Studio Test Platform
           inputs:
              packageFeedSelector: 'nugetOrg'
              versionSelector: 'latestPreRelease'
              
         - task: DownloadBuildArtifacts@0
           displayName: Download latest Automated tests binaries
           inputs:
              buildType: 'specific'
              project: 'fbaf94f7-2d40-410a-8a27-de142d8d2313'
              pipeline: '43'
              buildVersionToDownload: 'latestFromBranch'
              branchName: 'refs/heads/master'
              downloadType: 'single'
              artifactName: '_AutomatedTests'
              downloadPath: '$(System.ArtifactsDirectory)'

         - task: replacetokens@3
           displayName: Replace config settings
           inputs:
              rootDirectory: '$(System.ArtifactsDirectory)' 
              targetFiles: '**/*Behaviour*.config'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTelemetry: true

         - task: VSTest@2
           displayName: 'Run Blaise Smoke Tests'
           inputs:
             searchFolder: '$(System.ArtifactsDirectory)'
             testAssemblyVer2: |
              **\Blaise.Tests.Behaviour\**\Blaise.Tests.Behaviour.dll
              !**\obj\**
              resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
             runOnlyImpactedTests: false
             uiTests: true
             vsTestVersion: toolsInstaller
             runInParallel: false
             runTestsInIsolation: false
             codeCoverageEnabled: false
             testRunTitle: 'Instrument Test'
           continueOnError: false

  - stage: RestApi_${{parameters.Environment }}
    displayName: Installation Of RestAPI ${{parameters.Environment }}
    variables:
          ENV_RESTAPI_URL: http://localhost:90
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
          TEMP_PATH : c:\blaise\temp
          PACKAGE_EXTENSION : zip
    jobs:
       - deployment: InstallRestAPI
         displayName: Install Rest API
         environment: ${{parameters.Environment }}.RESTAPI
         strategy:
          runOnce:
             deploy:
               steps:
               - checkout: self 
               - task: DownloadSecureFile@1
                 displayName: 'Download GCP Key'
                 name: gcpkey
                 inputs:
                  secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'
              
               - task: PowerShell@2
                 displayName: Download Test instrument
                 inputs:
                  targetType: 'inline'
                  script: |
                    Write-Host "Login to GCP"
                        gcloud auth activate-service-account pipeline-bucket-reader@ons-blaise-v2-shared.iam.gserviceaccount.com --key-file=$(gcpkey.secureFilePath)
                        
                        Write-Host "Downloading instrument"
                        gsutil cp gs://ons-blaise-v2-europe-west2-shared-data/OPN2101A.zip c:\survey\OPN2101A.zip

                        Write-Host "GCP Login with compute service account"
                        gcloud auth login $env:ENV_VM_SERVICEACCOUNT

               - task: DownloadSecureFile@1
                 displayName: 'Download Blaise Registry settings file'
                 name: BlaiseRegistrySettings
                 inputs:
                   secureFile: blaise.reg

               - powershell: |
                  regedit /i /s $(BlaiseRegistrySettings.secureFilePath)	
                 displayName: 'Register Blaise License'
                
               - task: DownloadBuildArtifacts@0
                 displayName: Download REST API Artifact
                 inputs:
                  buildType: 'specific'
                  project: 'fbaf94f7-2d40-410a-8a27-de142d8d2313'
                  pipeline: '45'
                  buildVersionToDownload: 'latestFromBranch'
                  branchName: 'refs/heads/master'
                  downloadType: 'single'
                  artifactName: '_blaiseRestAPI'
                  downloadPath: '$(System.ArtifactsDirectory)'
                
               - task: replacetokens@3
                 displayName: Replace Config Settings
                 inputs:
                  rootDirectory: '$(System.ArtifactsDirectory)'
                  targetFiles: '**/*.config'
                  encoding: 'auto'
                  writeBOM: true
                  actionOnMissing: 'warn'
                  keepToken: false
                  tokenPrefix: '#{'
                  tokenSuffix: '}#'
                  useLegacyPattern: false
                  enableTelemetry: true
              
               - task: PowerShell@2
                 displayName: Deleting Current REST API Service
                 inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/delete-a-service.ps1'
                  arguments: '-ServiceName BlaiseRestApi'

               - task: CopyFiles@2
                 displayName: Copy REST API Binaries
                 inputs:
                  SourceFolder: '$(System.ArtifactsDirectory)/_BlaiseRestApi/Blaise.Api/bin/Release'
                  Contents: '**'
                  TargetFolder: 'c:\blaiseServices\BlaiseRestApi'
                  CleanTargetFolder: true
                  OverWrite: true

               - task: PowerShell@2
                 displayName: Create REST API Service
                 inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/create-a-service.ps1'
                  arguments: '-ServiceName BlaiseRestApi -exeName blaise.api'

               - task: VisualStudioTestPlatformInstaller@1
                 displayName: Install VS Test Platform
                 inputs:
                   packageFeedSelector: 'nugetOrg'
                   versionSelector: 'latestPreRelease'
                  
               - task: VSTest@2
                 displayName: Run REST API Smoke Tests
                 inputs:
                   testSelector: 'testAssemblies'
                   testAssemblyVer2: |
                     **\Blaise.Api.Tests.Behaviour\**\Blaise.Api.Tests.Behaviour.dll
                     !**\obj\**
                   searchFolder: '$(System.ArtifactsDirectory)'
                   vsTestVersion: 'toolsInstaller'
                  
  - stage: Configure_Blaise_${{parameters.Environment}}_
    displayName: Configure Blaise ${{parameters.Environment}}_
    variables:
          ENV_RESTAPI_URL: http://localhost:90
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)

    jobs: 
        - deployment: CheckUserRolesAlreadyExist
          displayName: Check User Roles already exist
          environment: ${{parameters.Environment }}.RESTAPI
          strategy:
           runOnce: 
             deploy:
               steps:
               - checkout: self

               - task: PowerShell@2
                 name: DoUserRolesExist
                 displayName: Check User Roles already exist
                 inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/UserRoles/CheckUserRolesAlreadyExist.ps1'
                
        - deployment: CreateUserRoles
          displayName: Create User Roles
          environment: ${{parameters.Environment }}.RESTAPI
          dependsOn: CheckUserRolesAlreadyExist
          condition: eq(dependencies.CheckUserRolesAlreadyExist.outputs['Deploy_RESTAPI.DoUserRolesExist.UserRolesExist'], 'False')          
          strategy:
           runOnce: 
             deploy:
               steps:
               - checkout: self

               - task: PowerShell@2
                 displayName: Create User Roles
                 inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/UserRoles/CreateUserRoles.ps1'
              
        - deployment: CheckUserRolesAreCreated
          displayName: Check User Roles Are Created
          environment: ${{parameters.Environment }}.RESTAPI
          dependsOn: CreateUserRoles
          condition: eq(dependencies.CreateUserRoles.outputs['Deploy_RESTAPI.DoUserRolesExist.UserRolesExist'], 'False')
          strategy:
           runOnce: 
             deploy:
               steps:
               - checkout: self

               - task: PowerShell@2
                 displayName: Check User Roles have been created
                 inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/UserRoles/CheckUserRolesAreCreated.ps1'
                
  - stage: RunUISmokeTests
    displayName: Run UI Smoke Tests
    variables:
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
          ENV_BLAISE_SERVER_HOST_NAME : $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
    jobs:
       - job: "UISmokeTests"
         pool: 
          vmImage: 'windows-latest'
         
         steps: 
         - task: DownloadSecureFile@1
           displayName: 'Download GCP Key'
           name: gcpkey
           inputs:
              secureFile: 'ons-blaise-v2-shared-221e50eb36c7.json'
         
         - task: DownloadSecureFile@1
           displayName: 'Download blaise registry file'
           name: BlaiseRegistrySettings
           inputs:
              secureFile: blaise.reg

         - powershell: |
            regedit /i /s $(BlaiseRegistrySettings.secureFilePath)	
           displayName: 'Register Blaise License'  

         - task: PowerShell@2
           displayName: Download test instrument
           inputs:
              targetType: 'inline'
              script: |
                Write-Host "Login to GCP"
                    gcloud auth activate-service-account pipeline-bucket-reader@ons-blaise-v2-shared.iam.gserviceaccount.com --key-file=$(gcpkey.secureFilePath)
                    
                    Write-Host "Downloading instrument"
                    gsutil cp gs://ons-blaise-v2-europe-west2-shared-data/OPN2101A.zip c:\survey\OPN2101A.zip

         - task: VisualStudioTestPlatformInstaller@1
           displayName: Install Visual Studio Test Platform
           inputs:
              packageFeedSelector: 'nugetOrg'
              versionSelector: 'latestPreRelease'                       
              
         - task: DownloadBuildArtifacts@0
           displayName: Download latest Automated tests binaries
           inputs:
              buildType: 'specific'
              project: 'fbaf94f7-2d40-410a-8a27-de142d8d2313'
              pipeline: '43'
              buildVersionToDownload: 'latestFromBranch'
              branchName: 'refs/heads/master'
              downloadType: 'single'
              artifactName: '_AutomatedTests'
              downloadPath: '$(System.ArtifactsDirectory)'

         - task: replacetokens@3
           displayName: Replace config settings
           inputs:
              rootDirectory: '$(System.ArtifactsDirectory)' 
              targetFiles: '**/*.config'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTelemetry: true  

         - task: VSTest@2
           displayName: 'Run CATI Smoke Tests'
           inputs:
             searchFolder: '$(System.ArtifactsDirectory)'
             testAssemblyVer2: |
              **\Blaise.cati.tests.behaviour\**\Blaise.cati.tests.behaviour.dll
              !**\obj\**
              resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
             runOnlyImpactedTests: false
             uiTests: true
             vsTestVersion: toolsInstaller
             runInParallel: false
             runTestsInIsolation: false
             codeCoverageEnabled: false
             testRunTitle: 'CATI Test'
           continueOnError: false

         - task: VSTest@2
           displayName: 'Run TOBI Smoke Tests'
           inputs:
             searchFolder: '$(System.ArtifactsDirectory)'
             testAssemblyVer2: |
              **\Blaise.tobi.tests.Behaviour\**\Blaise.tobi.tests.Behaviour.dll
              !**\obj\**
              resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
             runOnlyImpactedTests: false
             uiTests: true
             vsTestVersion: toolsInstaller
             runInParallel: false
             runTestsInIsolation: false
             codeCoverageEnabled: false
             testRunTitle: 'TOBI Test'
             testFiltercriteria: TestCategory=smoke
           continueOnError: false

         - task: VSTest@2
           displayName: 'Run DQS Smoke Tests'
           inputs:
             searchFolder: '$(System.ArtifactsDirectory)'
             testAssemblyVer2: |
              **\Blaise.DQS.tests.Behaviour\**\Blaise.DQS.tests.Behaviour.dll
              !**\obj\**
              resultsFolder: '$(System.DefaultWorkingDirectory)\TestResults'
             runOnlyImpactedTests: false
             uiTests: true
             vsTestVersion: toolsInstaller
             runInParallel: false
             runTestsInIsolation: false
             codeCoverageEnabled: false
             testRunTitle: 'DQS Test'
           continueOnError: false
