---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: IntegrationTestsBranch
    displayName: Branch to use
    default: main
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: BlaiseTests_${{parameters.Environment}}
    displayName: Blaise tests (${{parameters.Environment}})
    jobs:
      - job: BlaiseTests
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
          ENV_BLAISE_SERVER_HOST_NAME: $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
        pool:
          vmImage: windows-2019
        steps:
          - template: /templates/set_license_key.yml
            parameters:
              BlaiseLicenseKey: $(ENV_BLAISE_LICENSE_KEY)
              BlaiseActivationKey: $(ENV_BLAISE_ACTIVATION_CODE)
          - template: /templates/download_test_questionnaire.yml
          - template: /templates/download_build_artifact.yml
            parameters:
              Branch: ${{parameters.IntegrationTestsBranch}}
              ArtifactName: _AutomatedTests
              DownloadPath: $(System.ArtifactsDirectory)
              TargetFiles: '**/*Behaviour*.config'
              PipelineNumber: 43
          - template: /templates/run_tests_with_category.yml
            parameters:
              TestSolutionName: Blaise.Tests.Behaviour
              TestName: Blaise smoke tests
              TestCategory: Smoke
