parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use
  - name: AutomatedTestsBranch
    displayName: Automated tests git branch

trigger: none

pr: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages:
- stage: BlaiseInstall_${{parameters.Environment }}
  displayName: ${{parameters.Environment }} Installation Of Blaise
  jobs:
    - job: "SmokeTests"
      variables:
        ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
        ENV_BLAISE_SERVER_HOST_NAME : $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
      pool: 
        vmImage: 'windows-latest'
      steps:
      - template: /templates/blaise_reg_settings.yml

      - template: /templates/download_test_instrument.yml

      - template: /templates/download_artifact_steps.yml
        parameters: 
          GitBranch: ${{parameters.AutomatedTestsBranch}}
          ArtifactName: _AutomatedTests
          DownloadPath: $(System.ArtifactsDirectory)
          TargetFiles: '**/*Behaviour*.config'
          PipelineNumber: 43

      - template: /templates/automated_test_with_category_steps.yml
        parameters: 
          BehaviourSolutionName: Blaise.Tests.Behaviour
          TestName: Blaise Smoke Tests
          TestCategory: Smoke
