parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

pr: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages:
- stage: ConfigureUserRoles_${{parameters.Environment }}
  displayName: ${{parameters.Environment }} Configure User Roles
  variables:
        ENV_RESTAPI_URL: http://localhost:90
        ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
  jobs:
      - deployment: UserRoles
        displayName: Configure User Roles
        environment:  
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapi
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - template: /templates/user_roles_steps.yml
