parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  ENV_RESTAPI_URL: http://localhost:90
  ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)

stages:
- stage: ConfigureUserRoles_${{parameters.Environment }}
  displayName: ${{parameters.Environment }} Configure User Roles
  jobs:
      - deployment: InstallBlaise
        displayName: Install Blaise
        environment:  
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: blaise
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - template: /templates/check_user_roles_exist.yml

      #- job: "CreateUserRoles"
      #  dependsOn: CheckIfUserRolesExist
      #  condition: eq(dependencies.CheckIfUserRolesExist.outputs['Deploy_RESTAPI.DoUserRolesExist.UserRolesExist'], 'False')
      #  steps:
      #  - template: /templates/create_user_roles.yml
      #
      #  - template: /templates/check_user_roles_exist.yml