---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: ConfigureUserRoles_${{parameters.Environment}}
    displayName: Configure user roles (${{parameters.Environment}})
    variables:
      ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
    jobs:
      - deployment: UserRoles
        displayName: Configure user roles
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapitests
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: /templates/add_user_roles.yml
