---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: DeployBranch
    displayName: Branch to use
    default: main
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: DeployBlaiseCli_${{parameters.Environment}}
    displayName: Deploy Blaise CLI (${{parameters.Environment}})
    jobs:
      - deployment: DeployBlaiseCli
        displayName: Deploy Blaise CLI
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: blaise-cli
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: /templates/download_build_artifact.yml
                  parameters:
                    ${{ if notin(parameters.Environment, 'prod', 'preprod') }}:
                      Branch: ${{parameters.DeployBranch}}
                    ${{ if eq(parameters.Environment, 'prod') }}:
                      Branch: prod
                    ${{ if eq(parameters.Environment, 'preprod') }}:
                      Branch: preprod
                    ArtifactName: _BlaiseCli
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 66
                - template: /templates/copy_files.yml
                  parameters:
                    TargetFolder: c:\blaiseServices\BlaiseCli
                    SourceFolder: $(System.ArtifactsDirectory)/_BlaiseCli/Blaise.Cli/Blaise.Cli/bin/Release
