---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: DeployBranch
    displayName: Branch to use
    default: main
  - name: MaxParallel
    displayName: Number/percentage of targets to deploy to in parallel
    default: 50%
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: InstallRestApi_${{parameters.Environment}}
    displayName: Install REST API (${{parameters.Environment}})
    jobs:
      - deployment: InstallRestAPI
        displayName: Install REST API
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
          TESTING_URL: http://localhost/api/v2/health
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapi
        strategy:
          rolling:
            maxParallel: ${{parameters.MaxParallel}}
            preDeploy:
              steps:
                - checkout: self
                - template: /templates/remove_vm_from_instance_group.yml
                  parameters:
                    instancegroup: restapi-group
                    zone: europe-west2-a
            deploy:
              steps:
                - template: /templates/add_windows_firewall_rules.yml
                  parameters:
                    RuleName: Blaise
                    OutboundPorts: 80, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)
                    InboundPorts: 80, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)
                - template: /templates/set_windows_timezone.yml
                - template: /templates/add_cleanup_scheduler.yml
                - template: /templates/set_license_key.yml
                  parameters:
                    BlaiseLicenseKey: $(ENV_BLAISE_LICENSE_KEY)
                    BlaiseActivationKey: $(ENV_BLAISE_ACTIVATION_CODE)
                - template: /templates/download_build_artifact.yml
                  parameters:
                    ${{ if and(notin(parameters.Environment, 'prod', 'preprod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: ${{parameters.DeployBranch}}
                    ${{ if and(eq(parameters.Environment, 'prod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: prod
                    ${{ if and(eq(parameters.Environment, 'preprod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: preprod
                    ${{ if eq(parameters.DeployBranch, '5.14') }}:
                      Branch: ${{parameters.DeployBranch}}
                    ArtifactName: _BlaiseRestApi
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 60
                - template: /templates/deploy_windows_service.yml
                  parameters:
                    ServiceName: BlaiseRestApi
                    ExeName: blaise.api
                    TargetFolder: c:\BlaiseServices\BlaiseRestApi
                    SourceFolder: $(System.ArtifactsDirectory)/_BlaiseRestApi/Blaise.Api/bin/Release/net48
            routeTraffic:
              steps:
                - template: /templates/add_vm_to_instance_group.yml
                  parameters:
                    instancegroup: restapi-group
                    zone: europe-west2-a
