---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: DeployBranch
    displayName: Branch to use
    default: main

trigger: none
pr: none

variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml

stages:
  - stage: DeployBlaiseCli_${{parameters.Environment}}
    displayName: Deploy Blaise CLI (${{parameters.Environment}})
    jobs:
      - deployment: DeployBlaiseCli
        displayName: Deploy Blaise CLI
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: blaise-cli
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - template: /templates/install_mysql_connector.yml
                  parameters:
                    GCP_Bucket: $(ENV_BLAISE_GCP_BUCKET)

                - template: /templates/download_build_artifact.yml
                  parameters:
                    Branch: ${{parameters.DeployBranch}}
                    ArtifactName: _BlaiseCli
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 66

                - template: /templates/copy_files.yml
                  parameters:
                    TargetFolder: c:\BlaiseServices\BlaiseCli
                    SourceFolder: $(System.ArtifactsDirectory)/_BlaiseCli/Blaise.Cli/bin/Release/net48

                - template: /templates/add_windows_firewall_rules.yml
                  parameters:
                    RuleName: Blaise
                    InboundPorts: 80, 443, $(ENV_BLAISE_CONNECTION_PORT), $(ENV_BLAISE_REMOTE_CONNECTION_PORT)
                    OutboundPorts: 80, 443, $(ENV_BLAISE_CONNECTION_PORT), $(ENV_BLAISE_REMOTE_CONNECTION_PORT)

                - template: /templates/set_windows_timezone.yml
                - template: /templates/add_cleanup_scheduler.yml
