---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: DeployBranch
    displayName: Branch to use
    default: main
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: DeployBlaiseCli_${{parameters.Environment}}
    displayName: Deploy Blaise CLI (${{parameters.Environment}})
    jobs:
      - deployment: InstallMySqlConnector
        displayName: Install MySQL connector
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: blaise-cli
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: /templates/install_mysql_connector.yml
                  parameters:
                    GCP_Bucket: $($env:ENV_BLAISE_GCP_BUCKET)
      - deployment: DeployBlaiseCli
        displayName: Deploy Blaise CLI
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: blaise-cli
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: /templates/download_build_artifact.yml
                  parameters:
                    ${{ if and(notin(parameters.Environment, 'prod', 'preprod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: ${{parameters.DeployBranch}}
                    ${{ if and(eq(parameters.Environment, 'prod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: prod
                    ${{ if and(eq(parameters.Environment, 'preprod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: preprod
                    ${{ if eq(parameters.DeployBranch, '5.14') }}:
                      Branch: ${{parameters.DeployBranch}}
                    ArtifactName: _BlaiseCli
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 66
                - template: /templates/copy_files.yml
                  parameters:
                    TargetFolder: c:\BlaiseServices\BlaiseCli
                    SourceFolder: $(System.ArtifactsDirectory)/_BlaiseCli/Blaise.Cli/Blaise.Cli/bin/Release
                - template: /templates/add_windows_firewall_rules.yml
                  parameters:
                    RuleName: Blaise
                    InboundPorts: 80, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)
                    OutboundPorts: 80, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)
                - template: /templates/set_windows_timezone.yml
                - template: /templates/add_cleanup_scheduler.yml
