parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

pr: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml
  - name: env
    value: ${{ parameters.Environment }}

stages:
- stage: DQSTests_${{parameters.Environment }}
  displayName: ${{parameters.Environment }} DQS Automated Tests
  jobs:
    - job: "AutomatedTests"
      variables:
        ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
        ENV_BLAISE_SERVER_HOST_NAME : $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
      pool: 
        vmImage: 'windows-latest'
      steps:
      - template: /templates/blaise_reg_settings.yml

      - template: /templates/download_test_instrument.yml

      - template: /templates/download_artifact_steps.yml
        parameters: 
          GitBranch: 'master'
          ArtifactName: _AutomatedTests
          DownloadPath: $(System.ArtifactsDirectory)
          TargetFiles: '**/*Behaviour*.config'
          PipelineNumber: 43

      - ${{ if notin(parameters.Environment, 'preprod', 'dev') }}:
        - template: /templates/automated_test_with_category_steps.yml
          parameters: 
            BehaviourSolutionName: Blaise.DQS.Tests.Behaviour
            TestName: DQS Smoke Tests
            TestCategory: Smoke

      - ${{ if in(parameters.Environment, 'preprod', 'dev') }}:
        - template: /templates/automated_test_steps.yml
          parameters: 
            BehaviourSolutionName: Blaise.DQS.tests.Behaviour
            TestName: DQS Full Regression Tests
