---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: RestartBlaise_${{parameters.Environment}}
    displayName: Restart Blaise (${{parameters.Environment}})
    jobs:
      - deployment: RestartBlaise
        displayName: Restart Blaise
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: blaise
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: /templates/restart_windows_service.yml
                  parameters:
                    ServiceName: BlaiseServices5
