parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use
  - name: GitBranch
    displayName: Branch to deploy

trigger: none

pr: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages:
- stage: ${{parameters.Environment }}_BlaiseRESTAPI
  displayName: Installation Of RestAPI in ${{parameters.Environment }}
  jobs:
      - deployment: InstallRestAPI
        displayName: Install Rest API
        variables:
          ENV_RESTAPI_URL: http://localhost:90
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:  
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapi
        strategy:
          runOnce:
              deploy:
                steps:
                - checkout: self

                - template: /templates/blaise_reg_settings.yml

                - template: /templates/download_artifact_steps.yml
                  parameters: 
                    ${{ if notin(parameters.Environment, 'prod', 'preprod') }}:
                      GitBranch: ${{ parameters.GitBranch }}
                    ${{ if eq(parameters.Environment, 'prod') }}:
                      GitBranch: 'prod'
                    ${{ if eq(parameters.Environment, 'preprod') }}:
                      GitBranch: 'preprod'
                    ArtifactName: '_blaiseRestAPI'
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 60

                - template: /templates/deploy_service_steps.yml
                  parameters:
                    ServiceName: BlaiseRestApi
                    ExeName: blaise.api
                    TargetFolder: c:\blaiseServices\BlaiseRestApi
                    SourceFolder: $(System.ArtifactsDirectory)/_BlaiseRestApi/Blaise.Api/bin/Release



