parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use
  - name: GitBranch
    displayName: Branch to deploy

trigger: none

pr: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages:
- stage: ${{parameters.Environment }}_BlaiseRESTAPI
  displayName: Installation Of RestAPI in ${{parameters.Environment }}
  jobs:
      - deployment: InstallRestAPI
        displayName: Install Rest API
        variables:
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:  
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapi
        strategy:
          rolling:
            maxParallel: 50%
            preDeploy:
              steps:
              - task: PowerShell@2
                displayName: Restarting ${{parameters.ServiceName}} Service
                inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/helpers/GCP_Login_Auth.ps1'

              - task: PowerShell@2
                displayName: Restarting ${{parameters.ServiceName}} Service
                inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/helpers/modify_instance_groups.ps1'
                  arguments: 'removefromloadbalancer -instancegroup restapi-group -zone europe-west2-a'
            deploy:
              steps:
              - checkout: self

              - template: /templates/firewall_rule_steps.yml
                parameters:
                  RuleName: RestAPI
                  OutboundPorts: 80, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)
                  InboundPorts: 80, 90, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)

              - template: /templates/stackdriver_steps.yml
                parameters:
                  LoggingExe: StackdriverLogging-v1-14.exe
                  MonitoringExe: StackdriverMonitoring-GCM-46.exe
                  FolderPath: c:\dev\stackdriver

              - template: /templates/blaise_reg_settings.yml

              - template: /templates/download_artifact_steps.yml
                parameters: 
                  ${{ if notin(parameters.Environment, 'prod', 'preprod') }}:
                    GitBranch: ${{ parameters.GitBranch }}
                  ${{ if eq(parameters.Environment, 'prod') }}:
                    GitBranch: 'prod'
                  ${{ if eq(parameters.Environment, 'preprod') }}:
                    GitBranch: 'preprod'
                  ArtifactName: '_blaiseRestAPI'
                  DownloadPath: $(System.ArtifactsDirectory)
                  TargetFiles: '**/*.config'
                  PipelineNumber: 60

              - template: /templates/deploy_service_steps.yml
                parameters:
                  ServiceName: BlaiseRestApi
                  ExeName: blaise.api
                  TargetFolder: c:\blaiseServices\BlaiseRestApi
                  SourceFolder: $(System.ArtifactsDirectory)/_BlaiseRestApi/Blaise.Api/bin/Release
            routeTraffic:
              steps:
              - task: PowerShell@2
                displayName: Restarting ${{parameters.ServiceName}} Service
                inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/helpers/GCP_Login_Auth.ps1'

              - task: PowerShell@2
                displayName: Restarting ${{parameters.ServiceName}} Service
                inputs:
                  filePath: '$(Agent.BuildDirectory)/s/scripts/helpers/modify_instance_groups.ps1'
                  arguments: 'addtoloadbalancer -instancegroup restapi-group -zone europe-west2-a'
                    



