---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: Branch
    displayName: Branch to use
    default: main
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: RestApiTests_${{parameters.Environment}}
    displayName: REST API tests (${{parameters.Environment}})
    jobs:
      - deployment: RestApiTests
        displayName: REST API tests
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapitests
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/download_test_questionnaire.yml
                - template: /templates/download_build_artifact.yml
                  parameters:
                    ${{ if notin(parameters.Environment, 'preprod', 'prod') }}:
                      GitBranch: ${{parameters.IntegrationTestsBranch}}
                    ${{ if eq(parameters.Environment, 'prod') }}:
                      GitBranch: prod
                    ${{ if eq(parameters.Environment, 'preprod') }}:
                      GitBranch: preprod
                    ArtifactName: _RestApiTests
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 60
                - ${{ if notin(parameters.Environment, 'preprod', 'dev') }}:
                    - template: /templates/run_tests_with_category.yml
                      parameters:
                        BehaviourSolutionName: Blaise.Api.Tests.Behaviour
                        TestName: REST API smoke tests
                        TestCategory: Smoke
                - ${{ if in(parameters.Environment, 'preprod', 'dev') }}:
                    - template: /templates/run_tests.yml
                      parameters:
                        BehaviourSolutionName: Blaise.Api.Tests.Behaviour
                        TestName: REST API regression tests
