parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use
  - name: GitBranch
    displayName: Branch to deploy

trigger: none

pr: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages:
- stage: ${{parameters.Environment }}_BlaiseRESTAPI
  displayName: Installation Of RestAPI in ${{parameters.Environment }}
  jobs:
      - deployment: InstallRestAPI
        displayName: Install Rest API
        variables:
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:  
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapi
        strategy:
          rolling:
            maxParallel: 50%
            preDeploy:
              steps:
              - task: PowerShell@2
                displayName: Download SPSS Manipula Package
                inputs:
                  targetType: 'inline'
                  script: |
                    try
                    {
                      $hostname = hostname
                      Write-Host "hostname is: $hostname"
                      gcloud auth login $env:ENV_VM_SERVICEACCOUNT
                      gcloud compute instance-groups unmanaged remove-instances restapi-group --instances=$hostname --zone europe-west2-a
                      Write-Host "Removed $hostname from rest-api group"
                      gcloud config list
                    }
                    catch
                    {
                      Write-Host "Errored"
                      exit 1
                    }
                    
            deploy:
              steps:
              - checkout: self

              - template: /templates/firewall_rule_steps.yml
                parameters:
                  RuleName: RestAPI
                  OutboundPorts: 80, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)
                  InboundPorts: 80, 90, 443, $($env:ENV_BLAISE_CONNECTION_PORT), $($env:ENV_BLAISE_REMOTE_CONNECTION_PORT)

              - template: /templates/stackdriver_steps.yml
                parameters:
                  LoggingExe: StackdriverLogging-v1-14.exe
                  MonitoringExe: StackdriverMonitoring-GCM-46.exe
                  FolderPath: c:\dev\stackdriver

              - template: /templates/blaise_reg_settings.yml

              - template: /templates/download_artifact_steps.yml
                parameters: 
                  ${{ if notin(parameters.Environment, 'prod', 'preprod') }}:
                    GitBranch: ${{ parameters.GitBranch }}
                  ${{ if eq(parameters.Environment, 'prod') }}:
                    GitBranch: 'prod'
                  ${{ if eq(parameters.Environment, 'preprod') }}:
                    GitBranch: 'preprod'
                  ArtifactName: '_blaiseRestAPI'
                  DownloadPath: $(System.ArtifactsDirectory)
                  TargetFiles: '**/*.config'
                  PipelineNumber: 60

              - template: /templates/deploy_service_steps.yml
                parameters:
                  ServiceName: BlaiseRestApi
                  ExeName: blaise.api
                  TargetFolder: c:\blaiseServices\BlaiseRestApi
                  SourceFolder: $(System.ArtifactsDirectory)/_BlaiseRestApi/Blaise.Api/bin/Release
            routeTraffic:
              steps:
              - task: PowerShell@2
                displayName: Download SPSS Manipula Package
                inputs:
                  targetType: 'inline'
                  script: |
                    try
                    {
                      $hostname = hostname
                      Write-Host "hostname is: $hostname"
                      gcloud auth login $env:ENV_VM_SERVICEACCOUNT
                      gcloud compute instance-groups unmanaged add-instances restapi-group --instances=$hostname --zone europe-west2-a
                      Write-Host "Added $hostname back to rest-api group"
                    }
                    catch 
                    {
                      Write-Host "Errored"
                      exit 1
                    }
                    



