parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages: 
- stage: ServiceRestart
  variables: 
    - ServiceName: BlaiseServices5
  
  jobs:
    - job: "RestartAService"
      displayName: Restart A Service
    - template: /templates/Restart-A-Service.yml