parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use
  - name: GitBranch
    displayName: Branch to deploy

trigger: none

pr: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages:
- stage: ${{parameters.Environment }}_BlaiseRESTAPI
  displayName: Automated tests for RestAPI in ${{parameters.Environment }}
  jobs:
      - deployment: InstallRestAPI
        displayName: Install Rest API
        variables:
          ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:  
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapitests
        strategy:
          runOnce:
              deploy:
                steps:
                - template: /templates/download_test_instrument.yml

                - template: /templates/download_artifact_steps.yml
                  parameters: 
                    ${{ if notin(parameters.Environment, 'preprod', 'prod') }}:
                      GitBranch: ${{ parameters.GitBranch }}
                    ${{ if eq(parameters.Environment, 'prod') }}:
                      GitBranch: 'prod'
                    ${{ if eq(parameters.Environment, 'preprod') }}:
                      GitBranch: 'preprod'
                    ArtifactName: '_blaiseRestAPI'
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 60