parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages: 
- stage: ServiceRestart
  jobs:
    - job: "RestartAService"
      displayName: Restart A Service
    - template: /templates/restart-a-service.yml
      parameters: 
        ServiceName: BlaiseServices5