---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: IntegrationTestsBranch
    displayName: Branch to use
    default: main
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
  - name: env
    value: ${{parameters.Environment}}
stages:
  - stage: DqsTests_${{parameters.Environment}}
    displayName: DQS tests (${{parameters.Environment}})
    jobs:
      - job: DqsTests
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
          ENV_BLAISE_SERVER_HOST_NAME: $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
        pool:
          vmImage: windows-latest
        steps:
          - template: /templates/set_license_key.yml
            parameters:
              BlaiseLicenseKey: $(ENV_BLAISE_LICENSE_KEY)
              BlaiseActivationKey: $(ENV_BLAISE_ACTIVATION_CODE)
          - template: /templates/download_test_questionnaire.yml
          - template: /templates/download_build_artifact.yml
            parameters:
              Branch: ${{parameters.IntegrationTestsBranch}}
              ArtifactName: _BlaiseIntegrationTests
              DownloadPath: $(System.ArtifactsDirectory)
              TargetFiles: '**/*Behaviour*.config'
              PipelineNumber: 43
          - template: /templates/set_windows_culture.yml
          - ${{ if eq(parameters.Environment, 'prod') }}:
              - template: /templates/run_tests_with_category.yml
                parameters:
                  TestSolutionName: Blaise.DQS.Tests.Behaviour
                  TestName: DQS smoke tests
                  TestCategory: smoke
          - ${{ if ne(parameters.Environment, 'prod') }}:
              - template: /templates/run_tests.yml
                parameters:
                  TestSolutionName: Blaise.DQS.tests.Behaviour
                  TestName: DQS regression tests
