---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: DeployBranch
    displayName: Branch to use
    default: main
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: RestApiTests_${{parameters.Environment}}
    displayName: REST API tests (${{parameters.Environment}})
    jobs:
      - deployment: RestApiTests
        displayName: REST API tests
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_INTERNAL_SERVER_BINDING)
        environment:
          name: ${{parameters.Environment}}
          resourceType: virtualMachine
          tags: restapitests
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /templates/download_test_questionnaire.yml
                - template: /templates/download_build_artifact.yml
                  parameters:
                    ${{ if and(notin(parameters.Environment, 'prod', 'preprod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: ${{parameters.DeployBranch}}
                    ${{ if and(eq(parameters.Environment, 'prod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: prod
                    ${{ if and(eq(parameters.Environment, 'preprod'), ne(parameters.DeployBranch, '5.14')) }}:
                      Branch: preprod
                    ${{ if eq(parameters.DeployBranch, '5.14') }}:
                      Branch: ${{parameters.DeployBranch}}
                    ArtifactName: _BlaiseRestApi
                    DownloadPath: $(System.ArtifactsDirectory)
                    TargetFiles: '**/*.config'
                    PipelineNumber: 60
                - ${{ if eq(parameters.Environment, 'prod') }}:
                    - template: /templates/run_tests_with_category.yml
                      parameters:
                        TestSolutionName: Blaise.Api.Tests.Behaviour
                        TestName: REST API smoke tests
                        TestCategory: smoke
                - ${{ if ne(parameters.Environment, 'prod') }}:
                    - template: /templates/run_tests.yml
                      parameters:
                        TestSolutionName: Blaise.Api.Tests.Behaviour
                        TestName: REST API regression tests
