---
parameters:
  - name: VarGroup
    displayName: Variable group
  - name: Environment
    displayName: Environment to use
  - name: Branch
    displayName: Branch to use
    default: main
trigger: none
pr: none
variables:
  - group: ${{parameters.VarGroup}}
  - template: /templates/variables.yml
stages:
  - stage: TobiTests_${{parameters.Environment}}
    displayName: TOBI tests (${{parameters.Environment}})
    jobs:
      - job: TobiTests
        variables:
          ENV_BLAISE_SERVER_BINDING: $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
          ENV_BLAISE_SERVER_HOST_NAME: $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
        pool:
          vmImage: windows-2019
        steps:
          - template: /templates/set_blaise_license_key.yml
            parameters:
              BlaiseLicenseKey: $(ENV_BLAISE_LICENSE_KEY)
              BlaiseActivationKey: $(ENV_BLAISE_ACTIVATION_CODE)
          - template: /templates/download_test_questionnaire.yml
          - template: /templates/set_windows_culture.yml
          - template: /templates/download_build_artifact.yml
            parameters:
              GitBranch: ${{parameters.Branch}}
              ArtifactName: _TobiTests
              DownloadPath: $(System.ArtifactsDirectory)
              TargetFiles: '**/*Behaviour*.config'
              PipelineNumber: 43
          - ${{ if notin(parameters.Environment, 'preprod', 'dev') }}:
              - template: /templates/run_tests_with_category.yml
                parameters:
                  BehaviourSolutionName: Blaise.TOBI.Tests.Behaviour
                  TestName: TOBI smoke tests
                  TestCategory: Smoke
          - ${{ if in(parameters.Environment, 'preprod', 'dev') }}:
              - template: /templates/run_tests.yml
                parameters:
                  BehaviourSolutionName: Blaise.TOBI.tests.Behaviour
                  TestName: TOBI regression tests
