parameters:
  - name: VarGroup
    displayName: Variable Group
  - name: Environment
    displayName: Environment to use

trigger: none

variables:
  - group: ${{ parameters.VarGroup }}
  - template: /templates/variables.yml

stages:
- stage: TOBITests_${{parameters.Environment }}
  displayName: ${{parameters.Environment }} TOBI Automated Tests
  jobs:
    - job: "AutomatedTests"
      variables:
        ENV_BLAISE_SERVER_BINDING : $(ENV_BLAISE_EXTERNAL_SERVER_BINDING)
        ENV_BLAISE_SERVER_HOST_NAME : $(ENV_BLAISE_EXTERNAL_SERVER_HOST_NAME)
      pool: 
        vmImage: 'windows-latest'
      steps:
      - template: /templates/blaise_reg_settings.yml
      - template: /templates/download_test_instrument.yml
      - ${{ if notin('${{ parameters.Environment }}', 'prod', 'preprod') }}:
        - template: /templates/automated_test_with_category_steps.yml
          parameters: 
            BehaviourSolutionName: Blaise.Tests.Behaviour
            TestName: Instrument Test
            TestCategory: Smoke
      - ${{ if notin('${{ parameters.Environment }}', 'prod', 'preprod') }}:
        - template: /templates/automated_test_steps.yml
          parameters: 
            BehaviourSolutionName: Blaise.TOBI.tests.Behaviour
            TestName: TOBI Test
