parameters:
  BlaiseLicenseKey: ''
  BlaiseActivationKey: ''

steps: 
- task: PowerShell@2
  displayName: Register Blaise via registry
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/blaise_registry_hack.ps1'
    arguments: '-BLAISE_LICENSE_KEY ${{parameters.BlaiseLicenseKey}} -BLAISE_ACTIVATION_CODE ${{parameters.BlaiseActivationKey}}'
