steps: 
- task: PowerShell@2
  displayName: Install Blaise
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/check_blaise_is_installed.ps1'
  name: BlaiseVariables

- task: PowerShell@2
  displayName: Rewrite URL
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/blaise_url_rewrite.ps1'

- task: PowerShell@2
  displayName: Increase session time-out
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/increase_iis_timeout.ps1'
