steps:
- task: PowerShell@2
  condition: eq(variables.MultiNode, true)
  displayName: Configure Blaise node roles
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/blaise_node_roles.ps1'
