parameters:
  - name: BlaiseLicenseKey
    displayName: License key for Blaise
  - name: BlaiseActivationKey
    displayName: Activation key for Blaise
    
steps: 
- task: PowerShell@2
  displayName: Install Blaise
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/check_blaise_is_installed.ps1'
  name: BlaiseVariables
- task: PowerShell@2
  displayName: Update Blaise License
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/update_blaise_license.ps1'
    arguments: '-BLAISE_LICENSE_KEY ${{parameters.BlaiseLicenseKey}} -BLAISE_ACTIVATION_CODE ${{parameters.BlaiseActivationKey}}'

