---
steps:
  - task: PowerShell@2
    displayName: Update environment variables
    inputs:
      filePath: $(Agent.BuildDirectory)/s/scripts/update_environment_variables.ps1
  - task: PowerShell@2
    displayName: Configure node roles
    inputs:
      filePath: $(Agent.BuildDirectory)/s/scripts/blaise/node_roles/configure_node_roles.ps1
