steps:
- task: PowerShell@2
  displayName: Update Environment Variables
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/helpers/update_environment_variables.ps1'

- task: PowerShell@2
  displayName: Configure Blaise node roles
  inputs:
    filePath: '$(Agent.BuildDirectory)/s/scripts/Blaise/blaise_node_roles.ps1'
