name: PowerShell Analysis

on:
    pull_request:
      branches: [ main ]
    push:
      branches: [ main ]


jobs:
  analysis:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run PSScriptAnalyzer
        uses: microsoft/powershell@v1
        with:
          script: |
            Install-Module -Name PSScriptAnalyzer -Force -AllowClobber
            Invoke-ScriptAnalyzer -Path .\scripts\ -ExcludeRule PSAvoidUsingPositionalParameters -Recurse
