---
name: Run unit tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  pester:
    name: Run Pester
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run Pester command
        shell: pwsh
        run: |-
          Invoke-Pester .\scripts\* -Passthru
