name: Test PowerShell on Ubuntu
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]


jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Perform Pester tests
        shell: pwsh
        run: |
          Invoke-Pester .\scripts\* -Passthru